//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSRevitNodesUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSRevitNodesUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Results.
        /// </summary>
        internal static string AnalysisResults {
            get {
                return ResourceManager.GetString("AnalysisResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an analysis result..
        /// </summary>
        internal static string AnalysisResultSelection {
            get {
                return ResourceManager.GetString("AnalysisResultSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuiltIn Parameter Group.
        /// </summary>
        internal static string BuiltInParameterGroup {
            get {
                return ResourceManager.GetString("BuiltInParameterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a built-in parameter group..
        /// </summary>
        internal static string BuiltInParameterGroupSelectorDescription {
            get {
                return ResourceManager.GetString("BuiltInParameterGroupSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All built-in categories..
        /// </summary>
        internal static string CategoriesDescription {
            get {
                return ResourceManager.GetString("CategoriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Headers.
        /// </summary>
        internal static string ColumnHeaders {
            get {
                return ResourceManager.GetString("ColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Types.
        /// </summary>
        internal static string ColumnTypes {
            get {
                return ResourceManager.GetString("ColumnTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Level.
        /// </summary>
        internal static string DetailLevel {
            get {
                return ResourceManager.GetString("DetailLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Shape Room Bounding Option.
        /// </summary>
        internal static string DirectShapeRoomBoundingOption {
            get {
                return ResourceManager.GetString("DirectShapeRoomBoundingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Direct Shape Room Bounding Option..
        /// </summary>
        internal static string DirectShapeRoomBoundingOptionSelectorDescription {
            get {
                return ResourceManager.GetString("DirectShapeRoomBoundingOptionSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a divided surface..
        /// </summary>
        internal static string DividedSurfaceFamiliesSelection {
            get {
                return ResourceManager.GetString("DividedSurfaceFamiliesSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No structural column types available..
        /// </summary>
        internal static string DropDownNoColumnType {
            get {
                return ResourceManager.GetString("DropDownNoColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No structural framing types available..
        /// </summary>
        internal static string DropDownNoFramingType {
            get {
                return ResourceManager.GetString("DropDownNoFramingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge of Element Id.
        /// </summary>
        internal static string EdgeOfElementId {
            get {
                return ResourceManager.GetString("EdgeOfElementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an edge..
        /// </summary>
        internal static string EdgeSelection {
            get {
                return ResourceManager.GetString("EdgeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all the elements at the specified Level from the model..
        /// </summary>
        internal static string ElementsatLevelDescription {
            get {
                return ResourceManager.GetString("ElementsatLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all the elements which are visible in the active view..
        /// </summary>
        internal static string ElementsInActiveViewDescription {
            get {
                return ResourceManager.GetString("ElementsInActiveViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all elements of the specified category from the model..
        /// </summary>
        internal static string ElementsofCategoryDescription {
            get {
                return ResourceManager.GetString("ElementsofCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all elements of the specified family type from the model..
        /// </summary>
        internal static string ElementsofFamilyTypeDescription {
            get {
                return ResourceManager.GetString("ElementsofFamilyTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All elements in the active document of a given type..
        /// </summary>
        internal static string ElementsofTypeDescription {
            get {
                return ResourceManager.GetString("ElementsofTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All element subtypes..
        /// </summary>
        internal static string ElementTypesDescription {
            get {
                return ResourceManager.GetString("ElementTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to export column headers. Default is MultipleRows..
        /// </summary>
        internal static string ExportColumnHeadersDescription {
            get {
                return ResourceManager.GetString("ExportColumnHeadersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to qualify text fields. Default is DoubleQuote..
        /// </summary>
        internal static string ExportTextQualifierDescription {
            get {
                return ResourceManager.GetString("ExportTextQualifierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face of Element Id.
        /// </summary>
        internal static string FaceOfElementId {
            get {
                return ResourceManager.GetString("FaceOfElementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faces.
        /// </summary>
        internal static string Faces {
            get {
                return ResourceManager.GetString("Faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a face..
        /// </summary>
        internal static string FaceSelection {
            get {
                return ResourceManager.GetString("FaceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Type.
        /// </summary>
        internal static string FamilyType {
            get {
                return ResourceManager.GetString("FamilyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All family types available in the document..
        /// </summary>
        internal static string FamilyTypesDescription {
            get {
                return ResourceManager.GetString("FamilyTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Region Type.
        /// </summary>
        internal static string FilledRegionType {
            get {
                return ResourceManager.GetString("FilledRegionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing Filled Region Type from the active document..
        /// </summary>
        internal static string FilledRegionTypeSelectorDescription {
            get {
                return ResourceManager.GetString("FilledRegionTypeSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Pattern.
        /// </summary>
        internal static string FillPattern {
            get {
                return ResourceManager.GetString("FillPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available fill patterns..
        /// </summary>
        internal static string FillPatternsDescription {
            get {
                return ResourceManager.GetString("FillPatternsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Pattern Target.
        /// </summary>
        internal static string FillPatternTarget {
            get {
                return ResourceManager.GetString("FillPatternTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the fill pattern..
        /// </summary>
        internal static string FillPatternTargetDescription {
            get {
                return ResourceManager.GetString("FillPatternTargetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type.
        /// </summary>
        internal static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Types for Revit Filters.
        /// </summary>
        internal static string FilterTypeSelectorDescription {
            get {
                return ResourceManager.GetString("FilterTypeSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Type.
        /// </summary>
        internal static string FloorType {
            get {
                return ResourceManager.GetString("FloorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All floor types available in the document..
        /// </summary>
        internal static string FloorTypesDescription {
            get {
                return ResourceManager.GetString("FloorTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framing Types.
        /// </summary>
        internal static string FramingTypes {
            get {
                return ResourceManager.GetString("FramingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given a Family Instance or Type allows the user to select a parameter as a string..
        /// </summary>
        internal static string GetFamilyParameterDescription {
            get {
                return ResourceManager.GetString("GetFamilyParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Alignment.
        /// </summary>
        internal static string HorizontalAlignment {
            get {
                return ResourceManager.GetString("HorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the horizontal text alignment style..
        /// </summary>
        internal static string HorizontalTextAlignmentStyleSelectorDescription {
            get {
                return ResourceManager.GetString("HorizontalTextAlignmentStyleSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a level in the active document.
        /// </summary>
        internal static string LevelsDescription {
            get {
                return ResourceManager.GetString("LevelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Pattern.
        /// </summary>
        internal static string LinePattern {
            get {
                return ResourceManager.GetString("LinePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available line patterns..
        /// </summary>
        internal static string LinePatternsDescription {
            get {
                return ResourceManager.GetString("LinePatternsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model Element.
        /// </summary>
        internal static string ModelElementSelection {
            get {
                return ResourceManager.GetString("ModelElementSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select elements..
        /// </summary>
        internal static string ModelElementsSelection {
            get {
                return ResourceManager.GetString("ModelElementsSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active Revit document found..
        /// </summary>
        internal static string NoActiveDocumentFound {
            get {
                return ResourceManager.GetString("NoActiveDocumentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No family instances found in the divided surface..
        /// </summary>
        internal static string NoFamilyInstancesInDividedSurfaceWarning {
            get {
                return ResourceManager.GetString("NoFamilyInstancesInDividedSurfaceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No family parameters available..
        /// </summary>
        internal static string NoFamilyParameters {
            get {
                return ResourceManager.GetString("NoFamilyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No family types available..
        /// </summary>
        internal static string NoFamilyTypes {
            get {
                return ResourceManager.GetString("NoFamilyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No floor types available..
        /// </summary>
        internal static string NoFloorTypesAvailable {
            get {
                return ResourceManager.GetString("NoFloorTypesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No levels available..
        /// </summary>
        internal static string NoLevelsAvailable {
            get {
                return ResourceManager.GetString("NoLevelsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No types found..
        /// </summary>
        internal static string NoTypesFound {
            get {
                return ResourceManager.GetString("NoTypesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wall types available..
        /// </summary>
        internal static string NoWallTypesAvailable {
            get {
                return ResourceManager.GetString("NoWallTypesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Type.
        /// </summary>
        internal static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a parameter type..
        /// </summary>
        internal static string ParameterTypeSelectorDescription {
            get {
                return ResourceManager.GetString("ParameterTypeSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Performance Adviser rules..
        /// </summary>
        internal static string PerformanceAdviserDescription {
            get {
                return ResourceManager.GetString("PerformanceAdviserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Adviser Rules.
        /// </summary>
        internal static string PerformanceAdviserRules {
            get {
                return ResourceManager.GetString("PerformanceAdviserRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing Revit Phase from the active document..
        /// </summary>
        internal static string PhaseSelectorDescription {
            get {
                return ResourceManager.GetString("PhaseSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point on Element.
        /// </summary>
        internal static string PointOnElement {
            get {
                return ResourceManager.GetString("PointOnElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a point on a face..
        /// </summary>
        internal static string PointOnElementSelection {
            get {
                return ResourceManager.GetString("PointOnElementSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Level.
        /// </summary>
        internal static string PortDataALevelToolTip {
            get {
                return ResourceManager.GetString("PortDataALevelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All elements in the active document of a given type..
        /// </summary>
        internal static string PortDataAllElementsInDocumentToolTip {
            get {
                return ResourceManager.GetString("PortDataAllElementsInDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All visible elements in the active view..
        /// </summary>
        internal static string PortDataAllVisibleElementsToolTip {
            get {
                return ResourceManager.GetString("PortDataAllVisibleElementsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Category..
        /// </summary>
        internal static string PortDataCategoriesToolTip {
            get {
                return ResourceManager.GetString("PortDataCategoriesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Category.
        /// </summary>
        internal static string PortDataCategoryToolTip {
            get {
                return ResourceManager.GetString("PortDataCategoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements at the given level..
        /// </summary>
        internal static string PortDataElementAtLevelToolTip {
            get {
                return ResourceManager.GetString("PortDataElementAtLevelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of elements matching the query..
        /// </summary>
        internal static string PortDataElementsToolTip {
            get {
                return ResourceManager.GetString("PortDataElementsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element type..
        /// </summary>
        internal static string PortDataElementTypeToolTip {
            get {
                return ResourceManager.GetString("PortDataElementTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Family Type..
        /// </summary>
        internal static string PortDataFamilTypeToolTip {
            get {
                return ResourceManager.GetString("PortDataFamilTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Type or Instance.
        /// </summary>
        internal static string PortDataFamilySymbolToolTip {
            get {
                return ResourceManager.GetString("PortDataFamilySymbolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the current Revit project..
        /// </summary>
        internal static string PortDataLocationToolTip {
            get {
                return ResourceManager.GetString("PortDataLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SunSettings element..
        /// </summary>
        internal static string PortDataSunSettingToolTip {
            get {
                return ResourceManager.GetString("PortDataSunSettingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Numbering.
        /// </summary>
        internal static string RevisionNumbering {
            get {
                return ResourceManager.GetString("RevisionNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an way to number the revisions..
        /// </summary>
        internal static string RevisionNumberingSelectorDescription {
            get {
                return ResourceManager.GetString("RevisionNumberingSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Number Type.
        /// </summary>
        internal static string RevisionNumberType {
            get {
                return ResourceManager.GetString("RevisionNumberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a revision number type..
        /// </summary>
        internal static string RevisionNumberTypeSelectorDescription {
            get {
                return ResourceManager.GetString("RevisionNumberTypeSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing Revit Revision from the active document..
        /// </summary>
        internal static string RevisionSelectorDescription {
            get {
                return ResourceManager.GetString("RevisionSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Visibility.
        /// </summary>
        internal static string RevisionVisibility {
            get {
                return ResourceManager.GetString("RevisionVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the revision visilibity type..
        /// </summary>
        internal static string RevisionVisibilitySelectorDescription {
            get {
                return ResourceManager.GetString("RevisionVisibilitySelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Type.
        /// </summary>
        internal static string RuleType {
            get {
                return ResourceManager.GetString("RuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A View Schedule Filter Type..
        /// </summary>
        internal static string ScheduleFilterTypeDescription {
            get {
                return ResourceManager.GetString("ScheduleFilterTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Type.
        /// </summary>
        internal static string ScheduleTypes {
            get {
                return ResourceManager.GetString("ScheduleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Schedule Type..
        /// </summary>
        internal static string ScheduleTypeSelectorDescription {
            get {
                return ResourceManager.GetString("ScheduleTypeSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select analysis results from the document..
        /// </summary>
        internal static string SelectAnalysisResultsDescription {
            get {
                return ResourceManager.GetString("SelectAnalysisResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a divided surface and get its family instances..
        /// </summary>
        internal static string SelectDividedSurfaceFamiliesDescription {
            get {
                return ResourceManager.GetString("SelectDividedSurfaceFamiliesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an edge..
        /// </summary>
        internal static string SelectEdgeDescription {
            get {
                return ResourceManager.GetString("SelectEdgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple edges..
        /// </summary>
        internal static string SelectEdgesDescription {
            get {
                return ResourceManager.GetString("SelectEdgesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges.
        /// </summary>
        internal static string SelectEdgesPrefix {
            get {
                return ResourceManager.GetString("SelectEdgesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a face..
        /// </summary>
        internal static string SelectFaceDescription {
            get {
                return ResourceManager.GetString("SelectFaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select faces..
        /// </summary>
        internal static string SelectFaces {
            get {
                return ResourceManager.GetString("SelectFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple faces from the Revit document..
        /// </summary>
        internal static string SelectFacesDescription {
            get {
                return ResourceManager.GetString("SelectFacesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection is disabled when Dynamo run is disabled..
        /// </summary>
        internal static string SelectionIsDisabledDescription {
            get {
                return ResourceManager.GetString("SelectionIsDisabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a model element from the document..
        /// </summary>
        internal static string SelectModelElementDescription {
            get {
                return ResourceManager.GetString("SelectModelElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple elements from the Revit document..
        /// </summary>
        internal static string SelectModelElementsDescription {
            get {
                return ResourceManager.GetString("SelectModelElementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a point on a face..
        /// </summary>
        internal static string SelectPointonFaceDescription {
            get {
                return ResourceManager.GetString("SelectPointonFaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a UV on a face..
        /// </summary>
        internal static string SelectUVonFaceDescription {
            get {
                return ResourceManager.GetString("SelectUVonFaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the current Revit site location..
        /// </summary>
        internal static string SiteLocationDescription {
            get {
                return ResourceManager.GetString("SiteLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Location is not available in a family document..
        /// </summary>
        internal static string SiteLocationFamilyDocumentWarning {
            get {
                return ResourceManager.GetString("SiteLocationFamilyDocumentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}, Latitude: {1}, Longitude: {2}.
        /// </summary>
        internal static string SiteLocationToString {
            get {
                return ResourceManager.GetString("SiteLocationToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A spacing rule layout for calculating divided paths..
        /// </summary>
        internal static string SpacingRuleLayoutDescription {
            get {
                return ResourceManager.GetString("SpacingRuleLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a structural column type in the active document.
        /// </summary>
        internal static string StructuralColumnTypesDescription {
            get {
                return ResourceManager.GetString("StructuralColumnTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a structural framing type in the active document.
        /// </summary>
        internal static string StructuralFramingTypesDescription {
            get {
                return ResourceManager.GetString("StructuralFramingTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the SunSettings of the current View..
        /// </summary>
        internal static string SunSettingsCurrentDescription {
            get {
                return ResourceManager.GetString("SunSettingsCurrentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Qualifier.
        /// </summary>
        internal static string TextQualifier {
            get {
                return ResourceManager.GetString("TextQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV on Element.
        /// </summary>
        internal static string UVOnElement {
            get {
                return ResourceManager.GetString("UVOnElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Alignment.
        /// </summary>
        internal static string VerticalAlignment {
            get {
                return ResourceManager.GetString("VerticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the vertical text alignment style..
        /// </summary>
        internal static string VerticalTextAlignmentStyleSelectorDescription {
            get {
                return ResourceManager.GetString("VerticalTextAlignmentStyleSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Detail Level.
        /// </summary>
        internal static string ViewDetailLevelDescription {
            get {
                return ResourceManager.GetString("ViewDetailLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All views available in the current document..
        /// </summary>
        internal static string ViewsDescription {
            get {
                return ResourceManager.GetString("ViewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Location.
        /// </summary>
        internal static string WallLocation {
            get {
                return ResourceManager.GetString("WallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall locations..
        /// </summary>
        internal static string WallLocationLineDescription {
            get {
                return ResourceManager.GetString("WallLocationLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Type.
        /// </summary>
        internal static string WallType {
            get {
                return ResourceManager.GetString("WallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All wall types available in the document..
        /// </summary>
        internal static string WallTypesDescription {
            get {
                return ResourceManager.GetString("WallTypesDescription", resourceCulture);
            }
        }
    }
}
