//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSRevitNodesUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSRevitNodesUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All built-in categories..
        /// </summary>
        public static string CategoriesDescription {
            get {
                return ResourceManager.GetString("CategoriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all the elements at the specified Level from the model..
        /// </summary>
        public static string ElementsatLevelDescription {
            get {
                return ResourceManager.GetString("ElementsatLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all the elements which are visible in the active view..
        /// </summary>
        public static string ElementsInActiveViewDescription {
            get {
                return ResourceManager.GetString("ElementsInActiveViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all elements of the specified category from the model..
        /// </summary>
        public static string ElementsofCategoryDescription {
            get {
                return ResourceManager.GetString("ElementsofCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all elements of the specified family type from the model..
        /// </summary>
        public static string ElementsofFamilyTypeDescription {
            get {
                return ResourceManager.GetString("ElementsofFamilyTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All elements in the active document of a given type..
        /// </summary>
        public static string ElementsofTypeDescription {
            get {
                return ResourceManager.GetString("ElementsofTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All element subtypes..
        /// </summary>
        public static string ElementTypesDescription {
            get {
                return ResourceManager.GetString("ElementTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All family types available in the document..
        /// </summary>
        public static string FamilyTypesDescription {
            get {
                return ResourceManager.GetString("FamilyTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All floor types available in the document..
        /// </summary>
        public static string FloorTypesDescription {
            get {
                return ResourceManager.GetString("FloorTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given a Family Instance or Symbol, allows the user to select a parameter as a string..
        /// </summary>
        public static string GetFamilyParameterDescription {
            get {
                return ResourceManager.GetString("GetFamilyParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a level in the active document.
        /// </summary>
        public static string LevelsDescription {
            get {
                return ResourceManager.GetString("LevelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Level.
        /// </summary>
        public static string PortDataALevelToolTip {
            get {
                return ResourceManager.GetString("PortDataALevelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All elements in the active document of a given type..
        /// </summary>
        public static string PortDataAllElementsInDocumentToolTip {
            get {
                return ResourceManager.GetString("PortDataAllElementsInDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All visible elements in the active view..
        /// </summary>
        public static string PortDataAllVisibleElementsToolTip {
            get {
                return ResourceManager.GetString("PortDataAllVisibleElementsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Category.
        /// </summary>
        public static string PortDataCategoryToolTip {
            get {
                return ResourceManager.GetString("PortDataCategoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements at the given level..
        /// </summary>
        public static string PortDataElementAtLevelToolTip {
            get {
                return ResourceManager.GetString("PortDataElementAtLevelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of elements matching the query..
        /// </summary>
        public static string PortDataElementsToolTip {
            get {
                return ResourceManager.GetString("PortDataElementsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element type..
        /// </summary>
        public static string PortDataElementTypeToolTip {
            get {
                return ResourceManager.GetString("PortDataElementTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Family Type..
        /// </summary>
        public static string PortDataFamilTypeToolTip {
            get {
                return ResourceManager.GetString("PortDataFamilTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Symbol or Instance.
        /// </summary>
        public static string PortDataFamilySymbolToolTip {
            get {
                return ResourceManager.GetString("PortDataFamilySymbolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the current Revit project..
        /// </summary>
        public static string PortDataLocationToolTip {
            get {
                return ResourceManager.GetString("PortDataLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SunSettings element..
        /// </summary>
        public static string PortDataSunSettingToolTip {
            get {
                return ResourceManager.GetString("PortDataSunSettingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select analysis results from the document..
        /// </summary>
        public static string SelectAnalysisResultsDescription {
            get {
                return ResourceManager.GetString("SelectAnalysisResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a divided surface and get its family instances..
        /// </summary>
        public static string SelectDividedSurfaceFamiliesDescription {
            get {
                return ResourceManager.GetString("SelectDividedSurfaceFamiliesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an edge..
        /// </summary>
        public static string SelectEdgeDescription {
            get {
                return ResourceManager.GetString("SelectEdgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a face..
        /// </summary>
        public static string SelectFaceDescription {
            get {
                return ResourceManager.GetString("SelectFaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple faces from the Revit document..
        /// </summary>
        public static string SelectFacesDesciption {
            get {
                return ResourceManager.GetString("SelectFacesDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a model element from the document..
        /// </summary>
        public static string SelectModelElementDescription {
            get {
                return ResourceManager.GetString("SelectModelElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple elements from the Revit document..
        /// </summary>
        public static string SelectModelElementsDescription {
            get {
                return ResourceManager.GetString("SelectModelElementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a point on a face..
        /// </summary>
        public static string SelectPointonFaceDescription {
            get {
                return ResourceManager.GetString("SelectPointonFaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a UV on a face..
        /// </summary>
        public static string SelectUVonFaceDescription {
            get {
                return ResourceManager.GetString("SelectUVonFaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the current Revit site location..
        /// </summary>
        public static string SiteLocationDescription {
            get {
                return ResourceManager.GetString("SiteLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A spacing rule layout for calculating divided paths..
        /// </summary>
        public static string SpacingRuleLayoutDescription {
            get {
                return ResourceManager.GetString("SpacingRuleLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a structural column type in the active document.
        /// </summary>
        public static string StructuralColumnTypesDescription {
            get {
                return ResourceManager.GetString("StructuralColumnTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a structural framing type in the active document.
        /// </summary>
        public static string StructuralFramingTypesDescription {
            get {
                return ResourceManager.GetString("StructuralFramingTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the SunSettings of the current View..
        /// </summary>
        public static string SunSettingsCurrentDescription {
            get {
                return ResourceManager.GetString("SunSettingsCurrentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All views available in the current document..
        /// </summary>
        public static string ViewsDescription {
            get {
                return ResourceManager.GetString("ViewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All floor types available in the document..
        /// </summary>
        public static string WallTypesDescription {
            get {
                return ResourceManager.GetString("WallTypesDescription", resourceCulture);
            }
        }
    }
}
