name: DynamoRevit Issue
description: File an issue with DynamoRevit
projects: [DynamoDS/7]
body:
  - type: textarea
    attributes:
      label: Dynamo Version
      description: |
        Which version of Dynamo are you using?
        Go to **Dynamo > About** if you are not sure.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Revit Version
      description: Which version of Revit are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Operating System
      description: e.g Windows 10, Windows 11
    validations:
      required: false
  - type: textarea
    attributes:
      label: What did you do?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you see instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Stacktrace/logs
    validations:
      required: false
  - type: textarea
    attributes:
      label: Details
      description: |
        Links? References?
        _Tip: To attach screenshots/gifs or log files, click this area to highlight it and then drag files into it._
    validations:
      required: false
