//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An adaptive component could not be found or created..
        /// </summary>
        internal static string Adaptive_Component_Creation_Failed {
            get {
                return ResourceManager.GetString("Adaptive_Component_Creation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Results from Dynamo.
        /// </summary>
        internal static string AnalysisResultsDefaultDescription {
            get {
                return ResourceManager.GetString("AnalysisResultsDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo Analysis Results.
        /// </summary>
        internal static string AnalysisResultsDefaultName {
            get {
                return ResourceManager.GetString("AnalysisResultsDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of sample locations and samples is not equal..
        /// </summary>
        internal static string Array_Count_Mismatch {
            get {
                return ResourceManager.GetString("Array_Count_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Grid.
        /// </summary>
        internal static string CurtainGridPreview {
            get {
                return ResourceManager.GetString("CurtainGridPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Panel is not planar.
        /// </summary>
        internal static string CurtainPanelIsNotPlanar {
            get {
                return ResourceManager.GetString("CurtainPanelIsNotPlanar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Panel.
        /// </summary>
        internal static string CurtainPanelPreview {
            get {
                return ResourceManager.GetString("CurtainPanelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Panel should represent Revit panel.
        /// </summary>
        internal static string CurtainPanelShouldRepresentRevitPanel {
            get {
                return ResourceManager.GetString("CurtainPanelShouldRepresentRevitPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Panel is not rectangular.
        /// </summary>
        internal static string CurtainPannelIsNotRectangular {
            get {
                return ResourceManager.GetString("CurtainPannelIsNotRectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo Data.
        /// </summary>
        internal static string Dynamo_AVF_Data_Name {
            get {
                return ResourceManager.GetString("Dynamo_AVF_Data_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family={0}, Type={1}.
        /// </summary>
        internal static string FamilyInstancePreview {
            get {
                return ResourceManager.GetString("FamilyInstancePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family: {0}.
        /// </summary>
        internal static string FamilyPreview {
            get {
                return ResourceManager.GetString("FamilyPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Type: {0}, Family: {1}.
        /// </summary>
        internal static string FamilySymbolPreview {
            get {
                return ResourceManager.GetString("FamilySymbolPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level(Name={0}, Elevation={1}).
        /// </summary>
        internal static string LevelPreview {
            get {
                return ResourceManager.GetString("LevelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of divisions must be greater than 2!.
        /// </summary>
        internal static string NumberOfDivisionsMustBeGreaterThan2 {
            get {
                return ResourceManager.GetString("NumberOfDivisionsMustBeGreaterThan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Point: Location=(X={0}, Y={1}, Z={2}).
        /// </summary>
        internal static string ReferencePointPreview {
            get {
                return ResourceManager.GetString("ReferencePointPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Revit face with the corresponding tag could not be found..
        /// </summary>
        internal static string Tag_Lookup_Error {
            get {
                return ResourceManager.GetString("Tag_Lookup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied path is invalid..
        /// </summary>
        internal static string View_ExportAsImage_Path_Invalid {
            get {
                return ResourceManager.GetString("View_ExportAsImage_Path_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(Name = {1} ).
        /// </summary>
        internal static string ViewPreview {
            get {
                return ResourceManager.GetString("ViewPreview", resourceCulture);
            }
        }
    }
}
