//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An adaptive component could not be found or created..
        /// </summary>
        internal static string Adaptive_Component_Creation_Failed {
            get {
                return ResourceManager.GetString("Adaptive_Component_Creation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Results from Dynamo.
        /// </summary>
        internal static string AnalysisResultsDefaultDescription {
            get {
                return ResourceManager.GetString("AnalysisResultsDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo Analysis Results.
        /// </summary>
        internal static string AnalysisResultsDefaultName {
            get {
                return ResourceManager.GetString("AnalysisResultsDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value for imageProperty {0} is invalid. There is no {1} in {2}..
        /// </summary>
        internal static string AppearanceAssetElementPropertyPathInvalid {
            get {
                return ResourceManager.GetString("AppearanceAssetElementPropertyPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value for imageProperty {0} is invalid. There is no texture connected to {1} in {2}..
        /// </summary>
        internal static string AppearanceAssetElementPropertyPathNoConnect {
            get {
                return ResourceManager.GetString("AppearanceAssetElementPropertyPathNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply an Area Scheme..
        /// </summary>
        internal static string AreaSchemeArgumentException {
            get {
                return ResourceManager.GetString("AreaSchemeArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of sample locations and samples is not equal..
        /// </summary>
        internal static string Array_Count_Mismatch {
            get {
                return ResourceManager.GetString("Array_Count_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get location of attached group..
        /// </summary>
        internal static string AttachedGroupLocation {
            get {
                return ResourceManager.GetString("AttachedGroupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get base or survey point from document..
        /// </summary>
        internal static string CannotGetBaseOrSurveyPoint {
            get {
                return ResourceManager.GetString("CannotGetBaseOrSurveyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last opened view {0} , can&apos;t be delete.
        /// </summary>
        internal static string CantCloseLastOpenView {
            get {
                return ResourceManager.GetString("CantCloseLastOpenView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t modify {0} of this view.
        /// </summary>
        internal static string CantModifyInView {
            get {
                return ResourceManager.GetString("CantModifyInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a Category..
        /// </summary>
        internal static string CategoryArgumentException {
            get {
                return ResourceManager.GetString("CategoryArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified View Template is not valid for this View..
        /// </summary>
        internal static string CategoryVisibilityOverrideError {
            get {
                return ResourceManager.GetString("CategoryVisibilityOverrideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Revit CeilingType with that name could not be located in the document..
        /// </summary>
        internal static string CeilingTypeNotFound {
            get {
                return ResourceManager.GetString("CeilingTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find cell for panel.
        /// </summary>
        internal static string CellForPanelNotFound {
            get {
                return ResourceManager.GetString("CellForPanelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting child elements is not supported for this type of Element..
        /// </summary>
        internal static string ChildElementsNotSupported {
            get {
                return ResourceManager.GetString("ChildElementsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input PolyCurve is closed..
        /// </summary>
        internal static string CloseInputPolyCurveError {
            get {
                return ResourceManager.GetString("CloseInputPolyCurveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node may be removed in future version. Use CreateProjectParameterForAllCategories(string, string, SpecType, GroupType, bool) instead..
        /// </summary>
        internal static string CreateProjectParameterForAllCategoriesObsolete {
            get {
                return ResourceManager.GetString("CreateProjectParameterForAllCategoriesObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node may be removed in future version. Use CreateProjectParameter(string, string, SpecType, GroupType, bool, IEnumerable&lt;Category&gt;) instead..
        /// </summary>
        internal static string CreateProjectParameterObsolete {
            get {
                return ResourceManager.GetString("CreateProjectParameterObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node may be removed in future version. Use CreateSharedParameterForAllCategories(string, string, SpecType, GroupType, bool) instead..
        /// </summary>
        internal static string CreateSharedParameterForAllCategoriesObsolete {
            get {
                return ResourceManager.GetString("CreateSharedParameterForAllCategoriesObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node may be removed in future version. Use CreateSharedParameter(string, string, SpecType, GroupType, bool, IEnumerable&lt;Category&gt;) instead..
        /// </summary>
        internal static string CreateSharedParameterObsolete {
            get {
                return ResourceManager.GetString("CreateSharedParameterObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element has no Curtain Grid..
        /// </summary>
        internal static string CurtainGridNotFound {
            get {
                return ResourceManager.GetString("CurtainGridNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference should be to Face of the Element..
        /// </summary>
        internal static string CurtainGridReferenceError {
            get {
                return ResourceManager.GetString("CurtainGridReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalElement of Curtain Panel is not Panel..
        /// </summary>
        internal static string CurtainPanelInternalElementError {
            get {
                return ResourceManager.GetString("CurtainPanelInternalElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Panel is not planar.
        /// </summary>
        internal static string CurtainPanelIsNotPlanar {
            get {
                return ResourceManager.GetString("CurtainPanelIsNotPlanar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Panel is not rectangular.
        /// </summary>
        internal static string CurtainPanelIsNotRectangular {
            get {
                return ResourceManager.GetString("CurtainPanelIsNotRectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Panel should represent Revit panel.
        /// </summary>
        internal static string CurtainPanelShouldRepresentRevitPanel {
            get {
                return ResourceManager.GetString("CurtainPanelShouldRepresentRevitPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain System Type not found..
        /// </summary>
        internal static string CurtainSystemTypeNotFound {
            get {
                return ResourceManager.GetString("CurtainSystemTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve ist not planar. Please supply a planar curve..
        /// </summary>
        internal static string CurveIsNotPlanar {
            get {
                return ResourceManager.GetString("CurveIsNotPlanar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curves do not form a closed loop..
        /// </summary>
        internal static string CurveLoopNotClosed {
            get {
                return ResourceManager.GetString("CurveLoopNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Curve By Points with less than two points..
        /// </summary>
        internal static string CurveNeedsTwoPoints {
            get {
                return ResourceManager.GetString("CurveNeedsTwoPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You supplied an {0}, but we could not extract a CurveReference from it!.
        /// </summary>
        internal static string CurveReferenceExtractionDetail {
            get {
                return ResourceManager.GetString("CurveReferenceExtractionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires a ElementCurveReference extracted from a Revit Element! .
        /// </summary>
        internal static string CurveReferenceExtractionFailure {
            get {
                return ResourceManager.GetString("CurveReferenceExtractionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Curve Reference can only be obtained from an Element..
        /// </summary>
        internal static string CurveReferenceFailure {
            get {
                return ResourceManager.GetString("CurveReferenceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input curves should come from a Revit Element. You can use the {0} or {1} to turn this Curve into a Revit Element..
        /// </summary>
        internal static string CurveReferenceHint {
            get {
                return ResourceManager.GetString("CurveReferenceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a curve geometry..
        /// </summary>
        internal static string CurveRequired {
            get {
                return ResourceManager.GetString("CurveRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only create DirectShapes from Solids, Surfaces or Meshes..
        /// </summary>
        internal static string DirectShapeInvalidArgument {
            get {
                return ResourceManager.GetString("DirectShapeInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document does not support global parameters..
        /// </summary>
        internal static string DocumentDoesNotSupportGlobalParams {
            get {
                return ResourceManager.GetString("DocumentDoesNotSupportGlobalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is not a valid Family Document..
        /// </summary>
        internal static string DocumentNotFamilyDocument {
            get {
                return ResourceManager.GetString("DocumentNotFamilyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document is not workshared.
        /// </summary>
        internal static string DocumentNotWorkshared {
            get {
                return ResourceManager.GetString("DocumentNotWorkshared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use Sheet.Duplicate node to Duplicate sheets.
        /// </summary>
        internal static string DuplicateViewCantApplySheet {
            get {
                return ResourceManager.GetString("DuplicateViewCantApplySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo Data.
        /// </summary>
        internal static string Dynamo_AVF_Data_Name {
            get {
                return ResourceManager.GetString("Dynamo_AVF_Data_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected failure occurred when attempting to convert the solid into a Revit BRep.
        /// </summary>
        internal static string DynamoSolidToRevitBRepFailure {
            get {
                return ResourceManager.GetString("DynamoSolidToRevitBRepFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected failure occurred when attempting to convert the surface into a Revit BRep.
        /// </summary>
        internal static string DynamoSurfaceToRevitBRepFailure {
            get {
                return ResourceManager.GetString("DynamoSurfaceToRevitBRepFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element cannot be annotated.
        /// </summary>
        internal static string ElementCannotBeAnnotatedError {
            get {
                return ResourceManager.GetString("ElementCannotBeAnnotatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Element {0} {1} cannot be deleted.
        /// </summary>
        internal static string ElementCantDelete {
            get {
                return ResourceManager.GetString("ElementCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ElementType of the given name in the current Document.
        /// </summary>
        internal static string ElementTypeNameNotFound {
            get {
                return ResourceManager.GetString("ElementTypeNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot place empty schedule on sheet..
        /// </summary>
        internal static string EmptySchedule {
            get {
                return ResourceManager.GetString("EmptySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot place empty view on sheet..
        /// </summary>
        internal static string EmptyView {
            get {
                return ResourceManager.GetString("EmptyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point list is empty.
        /// </summary>
        internal static string EndPointListEmpty {
            get {
                return ResourceManager.GetString("EndPointListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point list contains null elements.
        /// </summary>
        internal static string EndPointListHasNulls {
            get {
                return ResourceManager.GetString("EndPointListHasNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Schedule Export Options..
        /// </summary>
        internal static string ExportOptionsArgumentException {
            get {
                return ResourceManager.GetString("ExportOptionsArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You supplied an {0}, but we could not extract a ElementFaceReference from it!.
        /// </summary>
        internal static string FaceReferenceExtractionDetail {
            get {
                return ResourceManager.GetString("FaceReferenceExtractionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires a ElementFaceReference extracted from a Revit Element! .
        /// </summary>
        internal static string FaceReferenceExtractionFailure {
            get {
                return ResourceManager.GetString("FaceReferenceExtractionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Face Reference can only be obtained from an Element..
        /// </summary>
        internal static string FaceReferenceFailure {
            get {
                return ResourceManager.GetString("FaceReferenceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input surfaces should come from a Revit Element. You can use the {0} to turn this Surface into a Revit Element, then extract a ElementFaceReference from it..
        /// </summary>
        internal static string FaceReferenceHint {
            get {
                return ResourceManager.GetString("FaceReferenceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node may be removed in future version. Use FamilyDocument.AddParameter(string, GroupType, SpecType, bool) instead..
        /// </summary>
        internal static string FamilyDocumentAddParameterObsolete {
            get {
                return ResourceManager.GetString("FamilyDocumentAddParameterObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the FamilyInstance.
        /// </summary>
        internal static string FamilyInstanceCreationFailure {
            get {
                return ResourceManager.GetString("FamilyInstanceCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A family with the specified name, {0}, could not be found in the document..
        /// </summary>
        internal static string FamilyNotFound {
            get {
                return ResourceManager.GetString("FamilyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FamilySymbol with the specified name does not exist in the document..
        /// </summary>
        internal static string FamilySymbolNotFound1 {
            get {
                return ResourceManager.GetString("FamilySymbolNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FamilySymbol with the specified name, {0}, does not exist in the Family..
        /// </summary>
        internal static string FamilySymbolNotFound2 {
            get {
                return ResourceManager.GetString("FamilySymbolNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FamilySymbol with the specified name, {0}, does not exist in the document..
        /// </summary>
        internal static string FamilySymbolNotFound3 {
            get {
                return ResourceManager.GetString("FamilySymbolNotFound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family type does not exist in the document..
        /// </summary>
        internal static string FamilyTypeDoesNotExist {
            get {
                return ResourceManager.GetString("FamilyTypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be found at: {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Revit FloorType with that name could not be located in the document..
        /// </summary>
        internal static string FloorTypeNotFound {
            get {
                return ResourceManager.GetString("FloorTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more geometries have failed to convert due to this error: .
        /// </summary>
        internal static string GeometryConversionFailure {
            get {
                return ResourceManager.GetString("GeometryConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get a geometry object from the current document using the provided reference.
        /// </summary>
        internal static string GeometryObjectReferenceFailure {
            get {
                return ResourceManager.GetString("GeometryObjectReferenceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one Tagged Local Elements..
        /// </summary>
        internal static string GetTaggedLocalElements {
            get {
                return ResourceManager.GetString("GetTaggedLocalElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one Tagged References..
        /// </summary>
        internal static string GetTaggedReferences {
            get {
                return ResourceManager.GetString("GetTaggedReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node may be removed in future version. Use GlobalParameter.ByName(string, SpecType).
        /// </summary>
        internal static string GlobalParameterByNameObsolete {
            get {
                return ResourceManager.GetString("GlobalParameterByNameObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Grid Element can only be created in a Revit Project..
        /// </summary>
        internal static string GridCreationFailure {
            get {
                return ResourceManager.GetString("GridCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property may be removed in future version. Use GroupType instead..
        /// </summary>
        internal static string GroupObsolete {
            get {
                return ResourceManager.GetString("GroupObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input list of parameters does not have the same number of values required by the adaptive component..
        /// </summary>
        internal static string InputParamsMismatch {
            get {
                return ResourceManager.GetString("InputParamsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input list of points does not have the same number of values required by the adaptive component..
        /// </summary>
        internal static string InputPointParamsMismatch {
            get {
                return ResourceManager.GetString("InputPointParamsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input list of UVs does not have the same number of values required by the adaptive component..
        /// </summary>
        internal static string InputUVParamsMismatch {
            get {
                return ResourceManager.GetString("InputUVParamsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value and the parameter values&apos; data types are incompatible..
        /// </summary>
        internal static string InputValueParameterValueTypeMismatch {
            get {
                return ResourceManager.GetString("InputValueParameterValueTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not obtain ImportInstance from imported Element.
        /// </summary>
        internal static string InstanceImportFailure {
            get {
                return ResourceManager.GetString("InstanceImportFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected category is not valid in this document..
        /// </summary>
        internal static string InvalidCategory {
            get {
                return ResourceManager.GetString("InvalidCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the curve for creating a column should be above the start of the curve..
        /// </summary>
        internal static string InvalidColumnBaseLocation {
            get {
                return ResourceManager.GetString("InvalidColumnBaseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is not a valid ElementId, GUID, string or int..
        /// </summary>
        internal static string InvalidElementId {
            get {
                return ResourceManager.GetString("InvalidElementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the structural element is not a valid curve..
        /// </summary>
        internal static string InvalidElementLocation {
            get {
                return ResourceManager.GetString("InvalidElementLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid end point list.
        /// </summary>
        internal static string InvalidEndPointList {
            get {
                return ResourceManager.GetString("InvalidEndPointList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected face cannot be used to create a wall. Please use a mass face instead..
        /// </summary>
        internal static string InvalidFace {
            get {
                return ResourceManager.GetString("InvalidFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterType is not valid..
        /// </summary>
        internal static string InvalidFilterType {
            get {
                return ResourceManager.GetString("InvalidFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id string is not valid for object of type {0}..
        /// </summary>
        internal static string InvalidForgeTypeId {
            get {
                return ResourceManager.GetString("InvalidForgeTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid GroupType..
        /// </summary>
        internal static string InvalidGroupType {
            get {
                return ResourceManager.GetString("InvalidGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element does not have a host..
        /// </summary>
        internal static string InvalidHost {
            get {
                return ResourceManager.GetString("InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PathOfTravel element..
        /// </summary>
        internal static string InvalidPathOfTravel {
            get {
                return ResourceManager.GetString("InvalidPathOfTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Shape cannot be edited..
        /// </summary>
        internal static string InvalidShapeEditor {
            get {
                return ResourceManager.GetString("InvalidShapeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start point list..
        /// </summary>
        internal static string InvalidStartPointList {
            get {
                return ResourceManager.GetString("InvalidStartPointList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry join order can only be switched when the elements are already joined..
        /// </summary>
        internal static string InvalidSwitchJoinOrder {
            get {
                return ResourceManager.GetString("InvalidSwitchJoinOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid view..
        /// </summary>
        internal static string InvalidView {
            get {
                return ResourceManager.GetString("InvalidView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height must be greater than 0 and less that 30000 ft.  You provided a height of {0} ft..
        /// </summary>
        internal static string InvalidWallHeight {
            get {
                return ResourceManager.GetString("InvalidWallHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Material with the given name does not exist in the current Document..
        /// </summary>
        internal static string MaterialNotFound {
            get {
                return ResourceManager.GetString("MaterialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelText Elements can only be created in a Family Document..
        /// </summary>
        internal static string ModelTextCreationFailure {
            get {
                return ResourceManager.GetString("ModelTextCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ModelTextType of the name, {0}, in the current Document..
        /// </summary>
        internal static string ModelTextTypeNotFound {
            get {
                return ResourceManager.GetString("ModelTextTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mullion should represent Revit&apos;s Mullion..
        /// </summary>
        internal static string MullionParseError {
            get {
                return ResourceManager.GetString("MullionParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple curves converted from the input curve element..
        /// </summary>
        internal static string MultipleCurvesIntroducedAfterConversion {
            get {
                return ResourceManager.GetString("MultipleCurvesIntroducedAfterConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple surfaces converted from the input face..
        /// </summary>
        internal static string MultipleSurfacesIntroducedAfterConversion {
            get {
                return ResourceManager.GetString("MultipleSurfacesIntroducedAfterConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already in use..
        /// </summary>
        internal static string NameAlreadyInUse {
            get {
                return ResourceManager.GetString("NameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a Name..
        /// </summary>
        internal static string NameArgumentException {
            get {
                return ResourceManager.GetString("NameArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element has no child Elements.
        /// </summary>
        internal static string NoChildElements {
            get {
                return ResourceManager.GetString("NoChildElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Elements to purge in the current document..
        /// </summary>
        internal static string NoElementsToPurge {
            get {
                return ResourceManager.GetString("NoElementsToPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements are not intersecting.
        /// </summary>
        internal static string NonIntersectingElements {
            get {
                return ResourceManager.GetString("NonIntersectingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element has no parent component.
        /// </summary>
        internal static string NoParentElement {
            get {
                return ResourceManager.GetString("NoParentElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shared parameter file found..
        /// </summary>
        internal static string NoSharedParameterFileFound {
            get {
                return ResourceManager.GetString("NoSharedParameterFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloorType has no structural material assigned.
        /// </summary>
        internal static string NoStructuralMaterialAssigned {
            get {
                return ResourceManager.GetString("NoStructuralMaterialAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FamilyInstance is not an adaptive component..
        /// </summary>
        internal static string NotAdaptiveComponentError {
            get {
                return ResourceManager.GetString("NotAdaptiveComponentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element not valid. Use an element from a BuiltInCategory..
        /// </summary>
        internal static string NotBuiltInCategory {
            get {
                return ResourceManager.GetString("NotBuiltInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least two {0} for a dimension..
        /// </summary>
        internal static string NotEnoughDataError {
            get {
                return ResourceManager.GetString("NotEnoughDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curves does not create closed horizontal loop..
        /// </summary>
        internal static string NotHorizontalInputPolyCurveError {
            get {
                return ResourceManager.GetString("NotHorizontalInputPolyCurveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is not a Host Element.
        /// </summary>
        internal static string NotHostElement {
            get {
                return ResourceManager.GetString("NotHostElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unjoin Elements that are not already joined..
        /// </summary>
        internal static string NotJoinedElements {
            get {
                return ResourceManager.GetString("NotJoinedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided input view is not a plan view..
        /// </summary>
        internal static string NotPlanView {
            get {
                return ResourceManager.GetString("NotPlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a positive integer.
        /// </summary>
        internal static string NotPositiveIntegerError {
            get {
                return ResourceManager.GetString("NotPositiveIntegerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the input curves are null..
        /// </summary>
        internal static string NullInputCurvesError {
            get {
                return ResourceManager.GetString("NullInputCurvesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of divisions must be greater than 2!.
        /// </summary>
        internal static string NumberOfDivisionsMustBeGreaterThan2 {
            get {
                return ResourceManager.GetString("NumberOfDivisionsMustBeGreaterThan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input PolyCurve is not closed..
        /// </summary>
        internal static string OpenInputPolyCurveError {
            get {
                return ResourceManager.GetString("OpenInputPolyCurveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter group..
        /// </summary>
        internal static string ParameterGroupNotFound {
            get {
                return ResourceManager.GetString("ParameterGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter found by that name..
        /// </summary>
        internal static string ParameterNotFound {
            get {
                return ResourceManager.GetString("ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s storage type is not an Element..
        /// </summary>
        internal static string ParameterStorageNotElement {
            get {
                return ResourceManager.GetString("ParameterStorageNotElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s storage type is not an integer..
        /// </summary>
        internal static string ParameterStorageNotInteger {
            get {
                return ResourceManager.GetString("ParameterStorageNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s storage type is not a number..
        /// </summary>
        internal static string ParameterStorageNotNumber {
            get {
                return ResourceManager.GetString("ParameterStorageNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s storage type is not a string..
        /// </summary>
        internal static string ParameterStorageNotString {
            get {
                return ResourceManager.GetString("ParameterStorageNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter type..
        /// </summary>
        internal static string ParameterTypeNotFound {
            get {
                return ResourceManager.GetString("ParameterTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property may be removed in future version. Use SpecType instead..
        /// </summary>
        internal static string ParameterTypeObsolete {
            get {
                return ResourceManager.GetString("ParameterTypeObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} has no storage type..
        /// </summary>
        internal static string ParameterWithoutStorageType {
            get {
                return ResourceManager.GetString("ParameterWithoutStorageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PointAnalysisDisplay.ByViewPointsAndValues instead..
        /// </summary>
        internal static string PointDataObsolete {
            get {
                return ResourceManager.GetString("PointDataObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a point geometry..
        /// </summary>
        internal static string PointRequired {
            get {
                return ResourceManager.GetString("PointRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revit does not support turning PolyCurves into ModelCurves. Try exploding your PolyCurve into multiple Curves..
        /// </summary>
        internal static string PolyCurvesConversionError {
            get {
                return ResourceManager.GetString("PolyCurvesConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revit can only create a ReferenceCurve in a Family Document..
        /// </summary>
        internal static string ReferenceCurveCreationFailure {
            get {
                return ResourceManager.GetString("ReferenceCurveCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferencePoint Elements can only be created in a Family Document..
        /// </summary>
        internal static string ReferencePointCreationFailure {
            get {
                return ResourceManager.GetString("ReferencePointCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a surface or edge on an element..
        /// </summary>
        internal static string ReferenceSelectFailure {
            get {
                return ResourceManager.GetString("ReferenceSelectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roof type not found..
        /// </summary>
        internal static string RoofTypeNotFound {
            get {
                return ResourceManager.GetString("RoofTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms are required to compute longest Paths of Travel..
        /// </summary>
        internal static string RoomsForLongestPathNotFound {
            get {
                return ResourceManager.GetString("RoomsForLongestPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of sample points and number of samples must be the same..
        /// </summary>
        internal static string SamplePointsMismatchError {
            get {
                return ResourceManager.GetString("SamplePointsMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error exporting this schedule..
        /// </summary>
        internal static string ScheduleExportError {
            get {
                return ResourceManager.GetString("ScheduleExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Schedule Type..
        /// </summary>
        internal static string ScheduleTypeArgumentException {
            get {
                return ResourceManager.GetString("ScheduleTypeArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply more than 0 locations..
        /// </summary>
        internal static string Sheet_NoLocationSet {
            get {
                return ResourceManager.GetString("Sheet_NoLocationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply more than 0 views.
        /// </summary>
        internal static string Sheet_NoViewsError {
            get {
                return ResourceManager.GetString("Sheet_NoViewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View count should Equals location count..
        /// </summary>
        internal static string Sheet_ViewLocationMismatch {
            get {
                return ResourceManager.GetString("Sheet_ViewLocationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set a prefix or suffix to avoid duplicate sheet number.
        /// </summary>
        internal static string SheetDuplicateNeedFix {
            get {
                return ResourceManager.GetString("SheetDuplicateNeedFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sheet number {0} exists, please change your prefix or suffix.
        /// </summary>
        internal static string SheetNumberExists {
            get {
                return ResourceManager.GetString("SheetNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of start point array doesn&apos;t match size of end point array.
        /// </summary>
        internal static string StartEndListSizeMismatch {
            get {
                return ResourceManager.GetString("StartEndListSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start points list is empty.
        /// </summary>
        internal static string StartPointListEmpty {
            get {
                return ResourceManager.GetString("StartPointListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point list contains null elements.
        /// </summary>
        internal static string StartPointListHasNulls {
            get {
                return ResourceManager.GetString("StartPointListHasNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FaceAnalysisDisplay.ByViewFacePointsAndValues instead..
        /// </summary>
        internal static string SurfaceDataObsolete {
            get {
                return ResourceManager.GetString("SurfaceDataObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Revit face with the corresponding tag could not be found..
        /// </summary>
        internal static string Tag_Lookup_Error {
            get {
                return ResourceManager.GetString("Tag_Lookup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum of three points is required to create a topography surface..
        /// </summary>
        internal static string TopographyNeedsThreePoints {
            get {
                return ResourceManager.GetString("TopographyNeedsThreePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ToposolidType of the given name in the current Document..
        /// </summary>
        internal static string ToposolidTypeNotFound {
            get {
                return ResourceManager.GetString("ToposolidTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not found in document..
        /// </summary>
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property may be removed in future version. Use SpecType instead..
        /// </summary>
        internal static string UnitTypeObsolete {
            get {
                return ResourceManager.GetString("UnitTypeObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use VectorAnalysisDisplay.ByViewPointsAndVectorValues instead..
        /// </summary>
        internal static string VectorDataObsolete {
            get {
                return ResourceManager.GetString("VectorDataObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied path is invalid..
        /// </summary>
        internal static string View_ExportAsImage_Path_Invalid {
            get {
                return ResourceManager.GetString("View_ExportAsImage_Path_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot place view on sheet as it is already on a sheet..
        /// </summary>
        internal static string ViewAlreadyPlacedOnSheet {
            get {
                return ResourceManager.GetString("ViewAlreadyPlacedOnSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This View {0} can&apos;t be duplicated.
        /// </summary>
        internal static string ViewCantBeDuplicated {
            get {
                return ResourceManager.GetString("ViewCantBeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0} could not be packed on the Sheet.  The sheet is {1} x {2} and the view to be added is {3} x {4}.
        /// </summary>
        internal static string ViewCantPackOnSheet {
            get {
                return ResourceManager.GetString("ViewCantPackOnSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View does not support annotations..
        /// </summary>
        internal static string ViewDoesNotSupportAnnotations {
            get {
                return ResourceManager.GetString("ViewDoesNotSupportAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewDuplicateOption is invalid, please set input number should be 0, 1, 2.
        /// </summary>
        internal static string ViewDuplicateOptionOutofRange {
            get {
                return ResourceManager.GetString("ViewDuplicateOptionOutofRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error exporting the image..
        /// </summary>
        internal static string ViewExportImageError {
            get {
                return ResourceManager.GetString("ViewExportImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to override existing image failed due to file lock. Please make sure that image is not currently open in another application..
        /// </summary>
        internal static string ViewExportImageLockedError {
            get {
                return ResourceManager.GetString("ViewExportImageLockedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The View name {0} exists, please change your prefix or suffix.
        /// </summary>
        internal static string ViewNameExists {
            get {
                return ResourceManager.GetString("ViewNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified View Type could not be found..
        /// </summary>
        internal static string ViewPlan_ViewFamilyNotFound {
            get {
                return ResourceManager.GetString("ViewPlan_ViewFamilyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Schedule Type is not supported..
        /// </summary>
        internal static string ViewUnsupportedScheduleType {
            get {
                return ResourceManager.GetString("ViewUnsupportedScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no WallType of the given name in the current Document..
        /// </summary>
        internal static string WallTypeNotFound {
            get {
                return ResourceManager.GetString("WallTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value for this parameter needs to be of type {0}..
        /// </summary>
        internal static string WrongStorageType {
            get {
                return ResourceManager.GetString("WrongStorageType", resourceCulture);
            }
        }
    }
}
